### ISSUE TITLE
Startup Error: Enclosing Method not found

### ISSUE THREAD

**Issue by AnselmC** [dajudge/testee.fi#1]
Hi,
I have just started to use testee.fi and unfortunately I am running into a problem from the get-go.
I am getting an Initialization Error: **org.jboss.weld.exceptions.DeploymentException: Enclosing method not found**.
I added the full stack trace below.
I added the Maven dependencies as described, with one caveat (should this be of relevance): I had to exclude the org.jboss.weld dependency because our Nexus repository doesn't have the correct weld-impl-parent version that is required by fi-testee-junit4-all.
```
		<dependency>
			<groupId>fi.testee</groupId>
			<artifactId>testeefi-junit4-all</artifactId>
			<version>0.6.1</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.weld</groupId>
					<artifactId>weld-core-impl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.7</version>
			<scope>test</scope>
		</dependency>
		<!-- The following is a workaround, because the version of weld-core-impl that testeefi uses is 2.4.3 and our nexus only has 2.4.5 -->
		<dependency>
			<groupId>org.jboss.weld</groupId>
			<artifactId>weld-core-impl</artifactId>
			<version>2.4.5.Final</version>
			<scope>test</scope>
		</dependency>
```
The testClass I am trying to run is as simple as can be:
`@RunWith(TestEEfi.class)
public class CommentServiceCoreFacadeTest {

	@Test
	public void runTest() {
		System.out.println("TEST");
	}

}`
Any idea what I'm doing wrongly?
(It works with @RunWith(Arquillian))

> org.jboss.weld.exceptions.DeploymentException: Enclosing method not found
> 	at org.jboss.weld.executor.AbstractExecutorServices.checkForExceptions(AbstractExecutorServices.java:66)
> 	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:43)
> 	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:51)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer.addClasses(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.bootstrap.BeanDeployment.createClasses(BeanDeployment.java:224)
> 	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:398)
> 	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)
> 	at fi.testee.runtime.DependencyInjectionRealm.init(DependencyInjectionRealm.java:85)
> 	at fi.testee.runtime.TestRuntime.<init>(TestRuntime.java:64)
> 	at fi.testee.runtime.TestRuntime.instance(TestRuntime.java:55)
> 	at fi.testee.junit4.TestEEfi.<init>(TestEEfi.java:47)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
> Caused by: java.lang.InternalError: Enclosing method not found
> 	at java.lang.Class.getEnclosingMethod(Class.java:1065)
> 	at sun.reflect.generics.scope.ClassScope.computeEnclosingScope(ClassScope.java:50)
> 	at sun.reflect.generics.scope.AbstractScope.getEnclosingScope(AbstractScope.java:78)
> 	at sun.reflect.generics.scope.AbstractScope.lookup(AbstractScope.java:96)
> 	at sun.reflect.generics.factory.CoreReflectionFactory.findTypeVariable(CoreReflectionFactory.java:110)
> 	at sun.reflect.generics.visitor.Reifier.visitTypeVariableSignature(Reifier.java:165)
> 	at sun.reflect.generics.tree.TypeVariableSignature.accept(TypeVariableSignature.java:43)
> 	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
> 	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
> 	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
> 	at sun.reflect.generics.repository.FieldRepository.getGenericType(FieldRepository.java:85)
> 	at java.lang.reflect.Field.getGenericType(Field.java:247)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedField.of(BackedAnnotatedField.java:28)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedFields.computeValue(BackedAnnotatedType.java:181)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedFields.computeValue(BackedAnnotatedType.java:174)
> 	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:49)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:157)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedFields.<init>(BackedAnnotatedType.java:174)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedFields.<init>(BackedAnnotatedType.java:174)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:63)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by dajudge** [comment]
Hello @AnselmC,

thanks for you feedback.

I just released a snapshot version 0.6.2-SNAPSHOT (which now uses Weld 2.4.5-Final internally) to the OSS snapshot repo https://oss.sonatype.org/content/repositories/snapshots/ 

Could you please check if using that SNAPSHOT dependency (and removing your weld exclusion / replacement dependency) solves your issue?

If this does not solve your issue we can pretty much rule out that your different Weld version is the culprit and we would need a minimal example to reproduce your issue.

Best regards,
Alex

**Comment by AnselmC** [comment]
Hi @dajudge,
Thanks for getting back so quickly!
I added the missing pom file for 2.4.3 to my local repository and was able to add the testeefi dependency without any exclusion and still get the same error.
Adding the SNAPSHOT version doesn't work either, unfortunately.

Best regards,
Anselm

**Comment by dajudge** [comment]
Hi @AnselmC 

since we can now rule out issues with the Weld version, could you please provide some (potentially minimal) example code that exhibits this behavior so I can reproduce the problem on my side?

Thanks for your help!

Best regards,
Alex

**Comment by AnselmC** [comment]
Hi @dajudge 
I should have mentioned earlier that the final exception is preceded by a bunch of ClassNotFound Exceptions.
It must have something to do with how the project is set-up since everything works fine when I try it in a new dummy project that uses the same ecplise and maven settings. Insofar I'm not sure if you can help...
But who knows :)
Here's an excerpt of the console log I mentioned above:

> 14:45:03.119 [main] DEBUG fi.testee.deployment.BeanArchiveDiscovery - Additional qualifying annotations: [interface org.junit.Test, interface org.junit.runner.RunWith]
> 14:45:07.812 [main] DEBUG fi.testee.deployment.BeanArchiveDiscovery - Bean archive discovery completed in 4896ms
> 14:45:14.949 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
> 14:45:14.965 [main] INFO org.jboss.weld.Version - WELD-000900: 2.4.3 (Final)
> 14:45:14.975 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap 
> 14:45:14.975 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap > startContainer 
> 14:45:14.993 [main] DEBUG org.jboss.weld.Configuration - WELD-001902: Following configuration was detected and applied: {}
> 14:45:14.996 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap > startContainer > initServices 
> 14:45:15.055 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000124: Using 4 threads for bootstrap
> 14:45:15.072 [main] DEBUG org.jboss.weld.Bootstrap - Using instantiator: org.jboss.weld.bean.proxy.DefaultProxyInstantiator
> 14:45:15.073 [main] DEBUG org.jboss.weld.BootstrapTracker -   END bootstrap > startContainer > initServices (76 ms)
> 14:45:15.105 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap > startContainer > builtinContexts 
> 14:45:15.193 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%ApplicationContext
> 14:45:15.204 [main] DEBUG org.jboss.weld.Reflection - WELD-000601: interface javax.inject.Singleton is missing @Target. Weld will use this annotation, however this may make the application unportable.
> 14:45:15.204 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%SingletonContext
> 14:45:15.209 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%BoundSessionContext
> 14:45:15.213 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%BoundConversationContext
> 14:45:15.217 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%BoundRequestContext
> 14:45:15.217 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%RequestContext
> 14:45:15.219 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%DependentContext
> 14:45:15.220 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%HttpSessionContext
> 14:45:15.222 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%HttpSessionDestructionContext
> 14:45:15.222 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%HttpConversationContext
> 14:45:15.223 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: WELD%AbstractBuiltInBean%deployment%HttpRequestContext
> 14:45:15.223 [main] DEBUG org.jboss.weld.BootstrapTracker -   END bootstrap > startContainer > builtinContexts (117 ms)
> 14:45:15.225 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap > startContainer > readDeploymentStructure 
> 14:45:15.267 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.268 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.269 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.269 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.270 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.270 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.271 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.271 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.272 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.272 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.272 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.273 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.273 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.273 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.274 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.274 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.275 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.275 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.276 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.276 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.277 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.277 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.278 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.278 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.278 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:15.278 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:15.280 [main] DEBUG org.jboss.weld.BootstrapTracker -   END bootstrap > startContainer > readDeploymentStructure (54 ms)
> 14:45:15.281 [main] DEBUG org.jboss.weld.BootstrapTracker -   END bootstrap > startContainer (305 ms)
> 14:45:15.281 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap > startInitialization 
> 14:45:17.652 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Extension [class org.jboss.weld.bootstrap.WeldExtension] with qualifiers [@Default]; n/a
> 14:45:17.652 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000168: Extension bean deployed: Extension [class org.jboss.weld.bootstrap.WeldExtension] with qualifiers [@Default]; n/a
> 14:45:17.653 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [javax.enterprise.inject.spi.BeanManager] with qualifiers [@Default]
> 14:45:17.653 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000106: Bean: Built-in Bean [org.jboss.weld.manager.BeanManagerImpl] with qualifiers [@Default]
> 14:45:17.656 [main] DEBUG org.jboss.weld.BootstrapTracker - START bootstrap > startInitialization > BeforeBeanDiscovery 
> 14:45:17.682 [main] DEBUG org.jboss.weld.Bootstrap - WELD-000162: BeforeBeanDiscovery.addAnnotatedType() called by org.jboss.weld.bootstrap.WeldExtension@7a419da4 for [BackedAnnotatedType] public @Vetoed @Interceptor @ActivateRequestContext @Priority class org.jboss.weld.context.activator.ActivateRequestContextInterceptor
> 14:45:17.682 [main] DEBUG org.jboss.weld.BootstrapTracker -   END bootstrap > startInitialization > BeforeBeanDiscovery (25 ms)
> 14:45:18.351 [weld-worker-4] INFO org.jboss.weld.Bootstrap - WELD-000119: Not generating any bean definitions from javax.mail.internet.InternetHeaders$MatchEnum because of underlying class loading error: Type [unknown] not found.  If this is unexpected, enable DEBUG logging to see the full error.
> 14:45:18.353 [weld-worker-4] DEBUG org.jboss.weld.Bootstrap - Catching
> org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class javax.mail.internet.InternetHeaders$MatchEnum
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IncompatibleClassChangeError: javax.mail.internet.InternetHeaders and javax.mail.internet.InternetHeaders$MatchEnum disagree on InnerClasses attribute
> 	at java.lang.Class.getDeclaringClass0(Native Method)
> 	at java.lang.Class.getDeclaringClass(Class.java:1235)
> 	at java.lang.Class.getEnclosingClass(Class.java:1277)
> 	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
> 	at java.lang.Class.isMemberClass(Class.java:1433)
> 	at org.jboss.weld.util.reflection.Reflections.getNesting(Reflections.java:138)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedConstructor.initParameters(BackedAnnotatedConstructor.java:50)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedConstructor.initParameters(BackedAnnotatedConstructor.java:28)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedCallable.<init>(BackedAnnotatedCallable.java:34)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedConstructor.<init>(BackedAnnotatedConstructor.java:38)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedConstructor.of(BackedAnnotatedConstructor.java:32)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:168)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:49)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:157)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:62)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	... 12 common frames omitted
> 14:45:18.817 [weld-worker-2] INFO org.jboss.weld.Bootstrap - WELD-000119: Not generating any bean definitions from org.glassfish.hk2.osgiresourcelocator.ServiceLoaderImpl because of underlying class loading error: Type org.osgi.framework.BundleListener not found.  If this is unexpected, enable DEBUG logging to see the full error.
> 14:45:18.817 [weld-worker-2] DEBUG org.jboss.weld.Bootstrap - Catching
> org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class org.glassfish.hk2.osgiresourcelocator.ServiceLoaderImpl
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: org/osgi/framework/BundleListener
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
> 	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
> 	at org.jboss.weld.annotated.slim.backed.SecurityActions.getDeclaredConstructors(SecurityActions.java:57)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:164)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:49)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:157)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:62)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	... 12 common frames omitted
> Caused by: java.lang.ClassNotFoundException: org.osgi.framework.BundleListener
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 31 common frames omitted
> 14:45:19.244 [weld-worker-1] INFO org.jboss.weld.Bootstrap - WELD-000119: Not generating any bean definitions from org.jboss.logging.JBossLogManagerLogger because of underlying class loading error: Type org.jboss.logmanager.Level not found.  If this is unexpected, enable DEBUG logging to see the full error.
> 14:45:19.245 [weld-worker-1] DEBUG org.jboss.weld.Bootstrap - Catching
> org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class org.jboss.logging.JBossLogManagerLogger
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: org/jboss/logmanager/Level
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
> 	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
> 	at org.jboss.weld.annotated.slim.backed.SecurityActions.getDeclaredConstructors(SecurityActions.java:57)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:164)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:49)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:157)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:161)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:62)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	... 12 common frames omitted
> Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Level
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 31 common frames omitted
> 14:45:19.765 [weld-worker-3] INFO org.jboss.weld.Bootstrap - WELD-000119: Not generating any bean definitions from jersey.repackaged.com.google.common.collect.ImmutableMultimap$2 because of underlying class loading error: Type [unknown] not found.  If this is unexpected, enable DEBUG logging to see the full error.
> 14:45:19.766 [weld-worker-3] DEBUG org.jboss.weld.Bootstrap - Catching
> org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class jersey.repackaged.com.google.common.collect.ImmutableMultimap$2
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.reflect.GenericSignatureFormatError: Signature Parse error: expected '<' or ';' or '.', got '/'.
> 	Remaining input: /repackaged/com/google/common/collect/ImmutableMultimap$Itr<TV;>;
> 	at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
> 	at sun.reflect.generics.parser.SignatureParser.parseSimpleClassTypeSignature(SignatureParser.java:367)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignatureSuffix(SignatureParser.java:378)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:312)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassSignature(SignatureParser.java:213)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassSig(SignatureParser.java:156)
> 	at sun.reflect.generics.repository.ClassRepository.parse(ClassRepository.java:57)
> 	at sun.reflect.generics.repository.ClassRepository.parse(ClassRepository.java:41)
> 	at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
> 	at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
> 	at sun.reflect.generics.repository.ClassRepository.<init>(ClassRepository.java:53)
> 	at sun.reflect.generics.repository.ClassRepository.make(ClassRepository.java:70)
> 	at java.lang.Class.getGenericInfo(Class.java:2548)
> 	at java.lang.Class.getTypeParameters(Class.java:713)
> 	at org.jboss.weld.util.Types.getCanonicalType(Types.java:143)
> 	at org.jboss.weld.util.Types.getCanonicalType(Types.java:158)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.initTypeClosure(BackedAnnotatedType.java:70)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotated.<init>(BackedAnnotated.java:19)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:58)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	... 12 common frames omitted
> 14:45:19.766 [weld-worker-2] INFO org.jboss.weld.Bootstrap - WELD-000119: Not generating any bean definitions from jersey.repackaged.com.google.common.collect.ImmutableMultimap$1 because of underlying class loading error: Type [unknown] not found.  If this is unexpected, enable DEBUG logging to see the full error.
> 14:45:19.767 [weld-worker-2] DEBUG org.jboss.weld.Bootstrap - Catching
> org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class jersey.repackaged.com.google.common.collect.ImmutableMultimap$1
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.reflect.GenericSignatureFormatError: Signature Parse error: expected '<' or ';' or '.', got '/'.
> 	Remaining input: /repackaged/com/google/common/collect/ImmutableMultimap$Itr<Ljava/util/Map$Entry<TK;TV;>;>;
> 	at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
> 	at sun.reflect.generics.parser.SignatureParser.parseSimpleClassTypeSignature(SignatureParser.java:367)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignatureSuffix(SignatureParser.java:378)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:312)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassSignature(SignatureParser.java:213)
> 	at sun.reflect.generics.parser.SignatureParser.parseClassSig(SignatureParser.java:156)
> 	at sun.reflect.generics.repository.ClassRepository.parse(ClassRepository.java:57)
> 	at sun.reflect.generics.repository.ClassRepository.parse(ClassRepository.java:41)
> 	at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
> 	at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
> 	at sun.reflect.generics.repository.ClassRepository.<init>(ClassRepository.java:53)
> 	at sun.reflect.generics.repository.ClassRepository.make(ClassRepository.java:70)
> 	at java.lang.Class.getGenericInfo(Class.java:2548)
> 	at java.lang.Class.getTypeParameters(Class.java:713)
> 	at org.jboss.weld.util.Types.getCanonicalType(Types.java:143)
> 	at org.jboss.weld.util.Types.getCanonicalType(Types.java:158)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.initTypeClosure(BackedAnnotatedType.java:70)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotated.<init>(BackedAnnotated.java:19)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:58)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	... 12 common frames omitted
> 14:45:19.770 [weld-worker-1] INFO org.jboss.weld.Bootstrap - WELD-000119: Not generating any bean definitions from org.hibernate.validator.internal.constraintvalidators.bv.past.PastValidatorForReadableInstant because of underlying class loading error: Type org.joda.time.ReadableInstant not found.  If this is unexpected, enable DEBUG logging to see the full error.
> 14:45:19.791 [weld-worker-1] DEBUG org.jboss.weld.Bootstrap - Catching
> org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class org.hibernate.validator.internal.constraintvalidators.bv.past.PastValidatorForReadableInstant
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:184)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:192)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:78)
> 	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
> 	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
> 	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
> 	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
> 	at org.jboss.weld.annotated.slim.backed.SecurityActions.getDeclaredMethods(SecurityActions.java:41)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:195)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:189)
> 	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:49)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:157)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:189)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:189)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:64)
> 	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:46)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:80)
> 	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:77)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:55)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache$1.apply(ReentrantMapBackedComputingCache.java:51)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:64)
> 	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
> 	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
> 	... 12 common frames omitted
> Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 31 common frames omitted

**Comment by dajudge** [comment]
If it's possible for you to post the dependencies section of the pom.xml of the failing project I could have a look at it and try to figure out what goes wrong...

**Comment by AnselmC** [comment]
@dajudge 
Talking to our build manage I finally realized that there's just a bunch of conflicts with dependencies (especially version managed one's) that are inherited. I will need to figure out how we're going to handle this.
Sorry for the unnecessary ticket!
Cheers

**Comment by dajudge** [comment]
@AnselmC Thanks for the feedback. Closing this issue. Should you encounter other problems please don't hesitate to open another issue :-)
